</div>
<img class="centerme" src="images/footernew.png"/>
<div class="centerme" style="width:730px;">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-7364299494566919";
/* Main-page-banner */
google_ad_slot = "1369821998";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<div class="centerme" style="color:white;width:460px;">
<p>
<a href="privacy-policy.html" target="_blank">Dungeon Studio Privacy Policy</a>
&#8226;
<a href="http://dsprototyping.com/booksign.html" target="_blank">Sign or guest book</a>

&#8226;
<a href="mailto:A4S8B7@dsprototyping.com">Contact DSP</a>
</p>
</div>


</body>
</html>
