10
CLS
SCREEN 2
PRINT "******************************************************************************"
PRINT "*                      AnDrEw BuCzKoS   mUsIc CoLeCtIoN                      *"
PRINT "*                                DeC. 20  1995                               *"
PRINT "******************************************************************************"
PRINT
PRINT "______________________________________________________________________________"
PRINT "[                                                                            ]"
PRINT "[     1,LoOnY tOoNs         4,AnDyS BoX       7,mAdLiBs    10,               ]"
PRINT "[     2,bArNy               5,LiTtLe StAr     8,mAsH       11,               ]"
PRINT "[     3,A qUaKe             6,MeLoDy          9,MaDlIbS2   12,               ]"
PRINT "[____________________________________________________________________________]"
INPUT "PLEASE MAKE A SELECTION, (99 TO EXIT)"; WIN
IF WIN = 99 THEN
        GOTO 37000
END IF
IF WIN = 1 THEN
        GOSUB 100
        END IF
IF WIN = 2 THEN
        GOSUB 200
        END IF
IF WIN = 3 THEN
        GOSUB 300
        END IF
IF WIN = 4 THEN
        GOSUB 400
        END IF
IF WIN = 5 THEN
        GOSUB 500
        END IF
IF WIN = 6 THEN
        GOSUB 600
        END IF
IF WIN = 7 THEN
        GOSUB 700
        END IF
IF WIN = 8 THEN
        GOSUB 800
        END IF
IF WIN = 9 THEN
        GOSUB 900
        END IF
IF WIN = 12 THEN
        GOSUB 1200
        END IF
IF WIN = 10 THEN
        GOSUB 1000
        END IF

GOTO 10
100
        CLS
        LOCATE 15, 30
        PRINT "LoOnIe !!!"
        PLAY "L8"
        PLAY "O3EDCDEE-ECDDDD2"
        PLAY "O3DCO2BO3CDD-DO2BO3CCCC2"
        PLAY "O2GG+AG+GG+AG+GGGG2"
        PLAY "O2GG+AG+GG+AG+GGGG2"
        PLAY "O3EDCDEE-ECDDDD2"
        PLAY "O2ABO3CD2EC"
RETURN
200
PRINT " sorry this part under constuction"
CLS
PRINT " sorry this part under constuction"
CLS
PRINT " sorry this part under constuction"
CLS
RETURN
300
        GOSUB 310
        GOSUB 310
        GOSUB 320
        GOSUB 310
        GOSUB 310
RETURN
310
        PLAY "L10"
        PLAY "O2 GO3 C2 CE2 EF O3 A2 O4C O3AG"
        PLAY "O3GA O3FD FGEC EFD O2B2A2G2"
RETURN
320
        PLAY "O2G O3E2DC2 O2A O3EDCO2BO3C"
RETURN
400
        CLS
        PRINT "            ___________________________"
        PRINT "            |                         |"
        PRINT "            |       ANDREWS           |"
        PRINT "            |                         |"
        PRINT "            |         box             |"
        PRINT "            |                         |"
        PRINT "            |_________________________|"
        PLAY "l9"
        PLAY "o3eeep12cegp12e "
        CLS
        PRINT "жррррррррррррррррррррррррррррррррррррррррррррррррррррррррррррррр©"
        PRINT "ннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннн"
        PRINT "ннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннн"
        PRINT "ннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннн"
        PRINT "ннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннн"
        PRINT "ннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннн"
        PRINT "ннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннн"
        PRINT "сввввввввввввввввввввввввввввввввввввввввввввввввввввввввввввввв╫"
        PRINT " сввввввввввввввввввввввввввввввввввввввввввввввввввввввввввввв╫"
        PRINT "  сппппппппппппппппппппппппппппппппппппппппппппппппппппппппппп╫"
        PRINT "жр©"
        PRINT "лнн"
        PRINT "сп╫"
        PLAY "L60"
        PLAY "O3CCCCCCCCCCCCCCCCCCCCC"
RETURN
500
        CLS
        PRINT
        PRINT
        LOCATE 15, 30
        PRINT "      TWINKLE TWINKLE LITTLE STAR"
        PLAY "O3CC"
        PLAY "O3GGO3AAO3G2"
        PLAY "O3FFEEDDC2"
        PLAY "O3GGFFEED2GGFFEED2"
        PLAY "O3CCGGAAG2FFEEDDC2"
        PLAY "O2G2E2C4"
RETURN
600
        CLS
' this song was made by andrew buczko
        PRINT
        PLAY "L8"
        PLAY "O3CO2GO3CECEGE"
        PLAY "O4CO3BAG2"
        PLAY "O4DCO3AGABO4CO3BAG2"
        PLAY "O3CO2GO3CECEGE"
        PLAY "O4CO3BAG2"
        PLAY "O4DCO3AGABO4CO3GO4EC2"
RETURN
700
        PRINT
        PRINT " ENTER A NUMBER"
        INPUT A
        PRINT " ENTER YOUR NAME"
        INPUT A$
        PRINT "ENTER YOUR AGE"
        INPUT B
        PRINT "TELL ME SOMTHING THAT IS VERY BAD TO DO."
        INPUT B$
        PRINT "GIVE ME A NOUN"
        INPUT C$
        CLS
        PRINT A$
        PRINT "IS A", B; "YEAR OLD", C$
        PRINT "THAT LIKES TO"; B$; A
        PRINT "TIMES A DAY!!"
        X$ = INPUT$(1)
RETURN
800
PRINT " THISI PART IS NOT DONE YET"
X$ = INPUT$(1)
RETURN
900
        CLS
        PRINT
        PRINT "             WELCOME TO THE WORLD OF MAD LIBS."
        PRINT
        PRINT "                      HAUNTED HOUSE"
        PRINT "   GIVE ME AN ADJECTIVE,DISCRIBES A NOUN OR PRONOUN."
        INPUT A$
        PRINT "   GIVE ME AN ADJECTIVE"
        INPUT B$
        PRINT " GIVE ME A PLURAL NOUN,MORE THAN ONE."
        INPUT C$
        PRINT " GIVE ME A PLURAL NOUN"
        INPUT D$
        PRINT "GIVE ME A PLURAL NOUN"
        INPUT E$
        PRINT "GIVE ME A VERB, PAST TENSE,RAN,SAW,KICKED."
        INPUT F$
        PRINT " GIVE ME A NOUN"
        INPUT G$
        PRINT " GIVE ME AN ADJECTIVE"
        INPUT H$
        PRINT " GIVE ME A PLURAL NOUN"
        INPUT I$
        PRINT " GIVE ME A NOUN"
        INPUT J$
        PRINT " GIVE ME A PLURAL NOUN"
        INPUT K$
        PRINT " GIVE ME A ADVERB,FAST,SLOW,WELL."
        INPUT L$
        PRINT " GIVE ME A NOUN"
        INPUT M$
        PRINT " GIVE ME A VERB,PAST TENSE"
        INPUT N$
        PRINT " GIVE ME A NOUN"
        INPUT O$
        PRINT " GIVE ME A PLURAL NOUN"
        INPUT P$
        PRINT " GIVE ME A NOUN"
        INPUT Q$
        PRINT " GIVE ME A PLURAL NOUN"
        INPUT R$
        PRINT " GIVE ME A PLURAL NOUN"
        INPUT S$
        PRINT " GIVE ME AN ADJECTIVE,DESCRIBES A NOUN OR PRONOUN."
        INPUT T$
        PRINT
        PRINT " ONCE THERE WAS A "; A$; " HOUSE IN SOME "; B$; " WOODS."
        PRINT " THIS HOUSE WAS HAUNTED BY "; C$; " AND "; D$; " SO WHEN "; E$
        PRINT " PASSED  IT, THEY "; F$; " .  ONE NIGHT,THOUGH,A "; G$; " DECIDED "
        PRINT " TO BE "; H$; " AND SPEND THE NIGHT. SOON HE HEARD "; I$; " RUNNING "
        PRINT " ARROUND. HE DIDN'T SEE A "; J$; ", BUT HE NEW "; K$; " WERE THERE."
        PRINT " SUDDENLY, SOMETHING HOWLED "; L$; ". HE THOUGHT IT MUST BE "
        PRINT " A "; M$; ". HE TRIED TO "; N$; " AWAY BUT GOT TANGLED UP IN A "; O$; "."
        PRINT " NOW HE NEW THE "; P$; " WERE GOING TO GET HIM, LOCK HIM UP IN"
        PRINT " THE "; Q$; ", AND MAYBE EVEN FEED HIM TO THE "; R$; ". BUT "
        PRINT " THE "; S$; " DIDN'T EVEN TOUCH HIM. WHEN HE WOKE UP THE NEXT MORNING "
        PRINT " HE NEW IT WAS JUST A "; T$; " DREAM."
        PRINT
        PRINT "                    THANK YOU FOR PLAYING "
        PRINT "              REDONE BY ANDREW BUCZKO,FOR QBASIC"
        PRINT "             PUSH PRINT SCREEN TO PRINT YOUR STORY"
        X$ = INPUT$(1)
       RETURN
1000
        LOCATE 18, 20
        SCREEN 2
        PRINT "ERROR!!!"
        PLAY "L40"
        PLAY "O1GGGGGGGG"
        CLS
        LOCATE 18, 20
        SCREEN 2
        PRINT "YOU DUMMY, WHAT DO YOU THINK YOUR DOING?!"
        PRINT " THIS IS NOT A VALID SELECTION."
RETURN
1200
        CLS
        LOCATE 15, 30
        PRINT "     FUR ELISE"
        PRINT "PROGRAMED BY ANDREW"
        PLAY "L6"
        PLAY "O4ED+ ED+ EO3BO4D O3CA"
RETURN
27000
        CLS
        PRINT
        PRINT
        PRINT
        PRINT "**********************SORRY THATS NOT A VALID SELECTION!**********************"
        X$ = INPUT$(1)
        GOTO 10
RETURN
37000
        END





